send message mutation
Ameelio/pathways-client pull request #115
Opened 2021-11-29 17:10 UTC by gabrielsaruhashi

## Proposed changes
Sends the message and updates the cache.
Ignore the yellow "focus" background on the demo :) . That has been removed

https://user-images.githubusercontent.com/12942772/143912212-89f9d87b-0c68-4d5f-8e6a-2e7cc1116bc3.mov

2021-11-29 17:43 UTC, cainlevy requested changes

2021-11-29 17:43 UTC, cainlevy commented on src/components/Inbox/MessageCompose.tsx
> +  loading?: boolean;
is loading used somewhere?

2021-11-29 17:43 UTC, cainlevy commented on src/components/Inbox/MessageList.tsx
> +  }, [focusRef, messages]);
if this `useEffect` is working properly, then i have to assume React runs it after updating `focusRef`. like, maybe react updates refs _during_ rendering and runs effects _after_ rendering.

2021-11-29 17:43 UTC, cainlevy commented on src/pages/InboxPage.tsx
> +        cache.updateQuery(
happy to help debug. i presume you were looking at https://github.com/Ameelio/connect-doc-client/pull/171/files#diff-a31867d783145cb05c11f8e76e954785362f0793829eefb0efa35c795096a122?

2021-11-29 17:43 UTC, cainlevy commented on src/pages/InboxPage.tsx
> +  }, [createError]);
sentry?

2021-11-29 18:15 UTC, gabrielsaruhashi commented on src/pages/InboxPage.tsx
> +        cache.updateQuery(
yep!

2021-11-29 18:16 UTC, gabrielsaruhashi commented on src/pages/InboxPage.tsx
> +        cache.updateQuery(
Is updateQuery incorrect?
It seems to accomplish the same as modify, but has less options/control

2021-11-29 18:40 UTC, cainlevy commented on src/pages/InboxPage.tsx
> +        cache.updateQuery(
`updateQuery` and `cache.modify` appear to accomplish roughly the same thing. `cache.modify` is lower-level and lets us operate on the normalized cache without the query abstraction.

i have found `cache.modify` to be more versatile because it lets me create decoupled form components. maybe it could work for us here, if we are very careful to colocate `useQuery` and `useMutation` hooks in our page components?

2021-11-30 13:09 UTC, gabrielsaruhashi commented on src/components/Inbox/MessageCompose.tsx
> +  loading?: boolean;
oop now it is!

2021-11-30 13:10 UTC, gabrielsaruhashi commented on src/components/Inbox/MessageList.tsx
> +  }, [focusRef, messages]);
actually, i realized I can actually simplify this a lot :) 
the use case was a bit different for DOC

2021-11-30 16:54 UTC, gabrielsaruhashi commented on src/utils/Message.ts
> +  return message.senderId === connection.visitor.malanId ? "visitor" : "inmate";
will move this computation to the server Resolver v soon :)

2021-11-30 16:58 UTC, cainlevy approved these changes

2021-11-30 16:58 UTC, cainlevy commented on src/utils/Message.ts
> +  return message.senderId === connection.visitor.malanId ? "visitor" : "inmate";
i see why it felt right to have `message.connection.visitor` previously.

what we really want is `message.sender: Visitor | Inmate`. is that part of the `malanId` refactor we talked about previously?

2021-11-30 17:00 UTC, gabrielsaruhashi commented on src/utils/Message.ts
> +  return message.senderId === connection.visitor.malanId ? "visitor" : "inmate";
yep!

2021-11-30 17:00 UTC, merged