Lp dashboard
Ameelio/pathways-client pull request #18
Opened 2021-02-25 15:34 UTC by lspdrz

## Proposed changes

Implements the redesign for Inmate Dashboard

## Related Issues

Closes Issue #13 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

We still need to do the following:
- Add Spanish translations
- Add Select Options to the dropdown on the CallCancelModal
- Contact the API cancel endpoint upon confirming that modal

2021-02-26 07:24 UTC, mpekala23 reviewed
left some comments! take or leave any of them, looks really good!

2021-02-26 07:24 UTC, mpekala23 commented on src/components/Dashboard/CallDetails.tsx
> +  onClose: Function;
nit: not a huge thing at all, but I personally am more used to typing functions as `() => void` (or whatever it would be). (Low key did not even know typing it like this was an option.) I slightly prefer `() => void` j because it's more clear a) arguments / return type b) if it's async or not. @gabrielsaruhashi thoughts?

2021-02-26 07:24 UTC, mpekala23 commented on src/components/Dashboard/CallDetails.tsx
> +      onClose={() => onClose()}
nit: I think you can j do `onClose={onClose}` (also slightly more performant bc doesn't create a function here as prop)

2021-02-26 07:24 UTC, mpekala23 commented on src/components/Dashboard/CallItem.tsx
> +  selectCall: Function;
same comment here re: typing as `(params: type) => returnType`, take or leave

2021-02-26 07:24 UTC, mpekala23 commented on src/components/Dashboard/CallsList.tsx
> +  selectCall: Function;
same here

2021-02-26 07:24 UTC, mpekala23 commented on src/components/Dashboard/ConnectionsList.tsx
> +  // TODO: Remove this messy function and pass the days past in the api endpoint
is this still needed?

2021-02-26 07:24 UTC, mpekala23 commented on src/components/Modals/CancelCallModal/CancelCallModal.tsx
> +const connector = connect(mapStateToProps, mapDispatchToProps);
nit: I've recently (like maybe a month ago?) started using the `useSelector` and `useDispatch` hooks over this type of const declaration + connector. slightly less code + easier to read imo. In order to more elegantly accept types as well, you can export your own version of these functions called `useTypedSelector` or something that auto-infers types v well

2021-02-26 07:24 UTC, mpekala23 commented on src/components/Modals/Modals.tsx
> +const connector = connect(mapStateToProps);
same comment of the `useSelector` hook

2021-02-26 07:24 UTC, mpekala23 commented on src/redux/index.ts
> +export const useAppDispatch = () => useDispatch<AppDispatch>(); // Export a hook that can be reused to resolve types
I think this is what I was talking about re: hooks (there's a similar one for `useSelector`, looks like something related is already included in the inputs?)

2021-02-26 08:17 UTC, lspdrz commented on src/components/Dashboard/CallDetails.tsx
> +  onClose: Function;
That makes sense to me!! Especially when considering arguments and return type. I'll go ahead and reimplement across the PR if you agree @gabrielsaruhashi

2021-02-26 08:18 UTC, lspdrz commented on src/components/Dashboard/ConnectionsList.tsx
> +  // TODO: Remove this messy function and pass the days past in the api endpoint
Yeah, for now. I made the function for this PR

2021-02-26 08:21 UTC, lspdrz commented on src/components/Modals/CancelCallModal/CancelCallModal.tsx
> +const connector = connect(mapStateToProps, mapDispatchToProps);
YEah, I wanted to discuss this with y'all. Are we trying to impose a standard redux convention where we only implement mapStateToProps instead of hooks or vice-versa? Or can we liberally use either/or when it makes sense?

I like the idea you're getting around above: using the mapState connector for large (parent-like) components only and then use the redux hooks in the smaller components. Thoughts? @gabrielsaruhashi

2021-02-26 08:25 UTC, lspdrz commented on src/components/Modals/CancelCallModal/CancelCallModal.tsx
> +const connector = connect(mapStateToProps, mapDispatchToProps);
Also, I was looking in the docs and found that if you define the state in the selector typescript infers for you: https://redux.js.org/recipes/usage-with-typescript#typing-the-useselector-hook

BUT, I don't think this would work if we use useSelector without a selector function (e.g. useSelector(state => state.auth.user). So agreed, I think it's best to just include the new useTypedSelector hook in the root redux file

2021-02-26 15:13 UTC, gabrielsaruhashi requested changes
some suggestions and nits!

2021-02-26 15:13 UTC, gabrielsaruhashi commented on src/components/Dashboard/CallDetails.tsx
> +  onClose: Function;
yep agreed!

2021-02-26 15:13 UTC, gabrielsaruhashi commented on src/components/Modals/CancelCallModal/CancelCallModal.tsx
> +const connector = connect(mapStateToProps, mapDispatchToProps);
makes sense!

Just gotta make sure we memoize selectors that return new objecst

2021-02-26 15:13 UTC, gabrielsaruhashi commented on src/components/Modals/CancelCallModal/CancelCallModal.tsx
> +const mapStateToProps = (state: RootState) => ({
@lspdrz , the convetion is to only connect containers to the store.

We should just pass down the id as a props to cancel call modal

2021-02-26 15:13 UTC, gabrielsaruhashi commented on src/components/Dashboard/DashboardHeader.tsx
> +          style={{ fontSize: "14px" }}
use level={5} instead of hardcoding it

2021-02-26 15:13 UTC, gabrielsaruhashi commented on src/components/Dashboard/DashboardHeader.tsx
> +            fontSize: "48px",
Use level={1} or somt instead of hardcoding

Btw do we need to hardcode padding? 
Cant we use the flexbox or Space

2021-02-26 15:13 UTC, gabrielsaruhashi commented on src/components/Modals/modalsSlice.ts
> +  cancelCall: Call | null;
I think it'd be cleaner to create some abstract interfaces to avoid having to add a new variable for every new modal

E.g

data: { entity: Call | User | ...; type: string }

and then you create  specific types:

entity: Call, type: call 

to use them on a switch statement

@mpekala23 has some really good examples of this strucutre

2021-02-26 18:34 UTC, lspdrz commented on src/components/Modals/CancelCallModal/CancelCallModal.tsx
> +const mapStateToProps = (state: RootState) => ({
Now doing this with a useSelector

2021-03-03 13:41 UTC, gabrielsaruhashi requested changes
Have a couple more comments/nit requests!

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/components/Dashboard/CallDetails.tsx
> +            <Col style={{ fontSize: 14 }}>
let's use tailwind's text-sm

for accessibility and modularity, we should use rem instead of hardcoding values

when we give users the option to adjust their font size, it'll be a matter of just updating the base HTML font size and all rem values will update

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/components/Dashboard/CallDetails.tsx
> +              <CalendarOutlined style={{ fontSize: "22px" }} />
same here

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/components/Dashboard/CallsList.tsx
> +          {calls.length === 0
Nit: I think it's cleaner to do 

!!calls.length ? 
             `${calls.length} ${t("call.upcomingCalls")}${
                calls.length > 1 ? "s" : ""
              }`   :  t("call.noCalls")

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/components/Dashboard/CallsList.tsx
> +      <div style={{ paddingBottom: 16 }}>
we should use tailwind instead of hardcoding padding values

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/components/Dashboard/ConnectionItem.tsx
> +    const last = Math.max.apply(
wait I think I had a comment on this function, but you can make this one line instead of looping twice over the array.

Check my last PR comments?

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/i18n/es/modals.json
> +  "cancelCallModal": {
Let's just do translations at the end? 

When everything is in

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/components/Dashboard/ConnectionsList.tsx
> +          .filter((connection) => connection.status === activeContactTab)
nit: for performance, i'd move this to a useState variable and use useEffect to update this array only when connections or tab changes 

Otherwise this will be re-rendered every single time

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/components/Dashboard/Dashboard.tsx
> +          style={{ padding: 24, paddingTop: 36 }}
would use tailwind

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/components/Dashboard/DashboardHeader.tsx
> +      className="w-full h-52 rounded-md bg-cover bg-center text-center flex-1 justify-end"
v nice!

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/i18n/es/modals.json
> +    "messageTwo": "Please select a cancellation reason to send to {{connectionFirstName}}.",
oh wow i didnt realize you could use templating language to pass down vars. v cool

2021-03-03 13:41 UTC, gabrielsaruhashi commented on src/pages/Dashboard/index.tsx
> +  return <Dashboard calls={calls} connections={connections} />;
isnt this pulverizing the component way too much?

Wondering if it's best to just have the dashboard component here and importing all components?

@mpekala23 would love to hear ur thoughts

2021-03-03 14:45 UTC, lspdrz commented on src/pages/Dashboard/index.tsx
> +  return <Dashboard calls={calls} connections={connections} />;
@gabrielsaruhashi Yep, but later on I would like to pitch implementing Next.js which uses this pages/ directory in a particular way. The pattern implemented here would scale to that

2021-03-03 18:26 UTC, gabrielsaruhashi approved these changes
final nits, but looks INCREDIBLE!

2021-03-03 18:26 UTC, gabrielsaruhashi commented on src/components/Dashboard/ConnectionsList.tsx
> +    setConnectionItems(
😍

2021-03-03 18:26 UTC, gabrielsaruhashi commented on src/components/Modals/CancelCallModal/CancelCallModal.tsx
> +        style={{ width: "100%" }}
nit let's use taiwind?

2021-03-03 18:26 UTC, gabrielsaruhashi commented on src/components/Modals/CancelCallModal/CancelCallModal.tsx
> +  const fullName = call ? genFullName(call.connection.user) : "";
Instead of having this check shouldnt we just do

if (!call) return <div /> ?

Then you don't need to check for call on every consecutive line

We might not even want to render the modal if it's going to be fully empty

2021-03-03 18:26 UTC, gabrielsaruhashi commented on src/components/Dashboard/Dashboard.tsx
> +            height: "60px",
nit: think it'd be good to move to a styles object liked you did on the other file

2021-03-03 18:26 UTC, gabrielsaruhashi commented on src/components/Dashboard/CallDetails.tsx
> +              <CalendarOutlined className="text-2xl" />
ay!

2021-03-03 18:52 UTC, lspdrz commented on src/components/Modals/CancelCallModal/CancelCallModal.tsx
> +  const fullName = call ? genFullName(call.connection.user) : "";
I agree with this, but I think we should save it for the new modal implementation I made an issue for. Particularly because if we just return an empty react component based on that call value, the parent modal will still render. We'll have to deal with this check on the parent modal when we move the call object there

2021-03-03 18:53 UTC, lspdrz commented on src/components/Dashboard/Dashboard.tsx
> +            height: "60px",
I actually need to abstract this whole div because we're using it in multiple places, so gonna leave like this now

2021-03-03 18:57 UTC, merged