Refactor/login user
Ameelio/pathways-client pull request #235
Opened 2022-04-05 09:35 UTC by crcommons

2022-04-05 15:22 UTC, cainlevy commented on src/graphql/queries/GetMe.graphql
> +      malanId
i wonder if we can drop this field as well? i'm hoping we can transition `malanId` into a private implementation detail.

2022-04-05 15:40 UTC, cainlevy commented on src/App.tsx
> +  const [token, setToken] = useLocalStorage("token", "");
we've historically only kept the api token in ephemeral page memory. i suspect the decision was originally made because pathways is accessed on shared computers in an environment where we want to discourage account sharing as much as is reasonable.

2022-04-05 15:40 UTC, cainlevy commented on src/App.tsx
> +                setUser={setUser}
right now it looks like ProtectedRoute needs `setUser` to load the current user's information. what if that responsibility lived here in App.tsx? i have a sense that it may be nice to co-locate the token & current user management, so we don't spread awareness of the difference between having a token and having a session.

2022-04-05 15:40 UTC, cainlevy commented on src/api/apollo.tsx
> +  const token = localStorage.getItem("token");
ohhh this must be why you decided on `localStorage`. hmm. i see the challenge but i do think we need a solution that won't persist through page reloads.

2022-04-05 15:40 UTC, cainlevy commented on src/pages/Login/index.tsx
> +          "Unable to login at this time.", // how to send login errors vs. connection issues
yeah it seems especially important to identify credentials issues

2022-04-11 12:13 UTC, crcommons commented on src/App.tsx
> +                setUser={setUser}
There is an issue that because app will try to run the user query even though you're not logged in. I attempted to move it to app and only run the query if we have the token, but there were some issues with the infinite re-render.

2022-04-11 20:01 UTC, cainlevy requested changes
i think we're getting close!

please use your discretion on some of these. i'm most interested in maintaining behavior on page reloads with a tweak to `useSessionStorage`.

in a future (unplanned) iteration we could also consider:

- React context
- revisiting the routes list

2022-04-12 06:05 UTC, crcommons commented on src/App.tsx
> +  // This needs to be defined within a react component
Yes and because you can't provide a jsx value outside of react

2022-04-12 06:26 UTC, crcommons commented on src/pages/Login/index.tsx
>    }
That's one reason, but it existed before because if you navigate to /login, we need to push you back to the home page. I just needed to make the change because 1) we're not using session.isLoggedIn anymore and 2) I read the it's preferable to use history.push over the redirect component.

2022-04-12 06:51 UTC, crcommons commented on src/pages/CallFeedback.tsx
> +type TParams = { id?: string; exitType?: CallExitType };
Yes :(

Maybe we can look at it later today

2022-04-12 06:51 UTC, crcommons commented on src/hooks/useAuthInfo.ts
> +  };
that was a different problem with usestate. This hook has been working like a dream :)

2022-04-14 17:50 UTC, cainlevy approved these changes

2022-04-15 14:43 UTC, merged