sc-3370 added toasts/copy for connection state changes
Ameelio/pathways-client pull request #253
Opened 2022-04-22 00:25 UTC by jackofsometrade

2022-04-22 00:27 UTC, jackofsometrade commented
Oops looks like the test action will fail until we merge and release a new connect-call-client...

2022-04-22 14:28 UTC, wittejm submitted a review, later dismissed

2022-04-22 14:28 UTC, wittejm commented on src/components/Call/Call.tsx
> +                  t("call:connectionQuality.poor"),
What do you think of using this new approach of i18n I'm trying? Content text as translation keys so we can still see content language in-line: 
https://github.com/Ameelio/pathways-client/blob/187a760f3293b566e7931bc41364700e8e8fd667/src/components/Inbox/VoiceCall/StartVoiceCallModal.tsx#L66

2022-04-22 14:28 UTC, wittejm commented on src/components/Call/Call.tsx
> +    // const toggleVideoRef = useRef<() => void>();
What are these?

2022-04-22 17:56 UTC, cainlevy commented on src/components/Call/Call.tsx
> +                ),
https://www.i18next.com/translation-function/interpolation

2022-04-23 00:04 UTC, jackofsometrade commented on src/components/Call/Call.tsx
> +    // const toggleVideoRef = useRef<() => void>();
Leftover pasta from connect-mobile, deleting.

2022-04-27 16:23 UTC, cainlevy requested changes
really close, i promise!

i'm mostly wary of how much transition effect awareness is built into the useEffect that watches the current user's connection state. the issue, i think, is how the callback is responsible for properly maintaining a `videoDisabled` value. let's talk and see if we can refine the pattern!

everything else is easily deferred polish or code golf.

2022-04-27 16:23 UTC, cainlevy commented on src/components/Call/Call.tsx
> +          if (!videoDisabled) {
i find it easier to read code with an early return because i don't have to scan for the matching brace and mind the indentation, e.g.:

```
if (!videoDisabled) break;
```

2022-04-27 16:23 UTC, cainlevy commented on src/components/Call/Call.tsx
> +    const peerConnectionQualityRef = useRef<Quality>();
i saw a hook in cmob that might help relocate some of this complexity. it was a version of `useEffect` that would be triggered by certain value transitions.

the exact implementation may not be perfect but the concept might be really helpful:

https://github.com/Ameelio/connect-mobile/blob/main/src/utils/hooks/useChange.ts

imagine something like:

```
useTransition({to: "bad"}, () => {
});

useTransition({from: ["bad", "poor"], to: ["good", "excellent", "average"]}, () => {
});
```

2022-04-27 16:35 UTC, jackofsometrade commented on src/components/Call/VideoOverlay.tsx
> +  videoDisabled: boolean;
yeah we can change it to something more obvious

2022-04-27 16:37 UTC, jackofsometrade commented on src/components/Call/Call.tsx
> +    useEffect(() => {
Sure thing, that helps me too.

2022-04-27 19:37 UTC, cainlevy approved these changes
wow `useChange` had a bigger impact than i expected!

(i'm resisting the temptation to play golf with the imported code 🤐 )

2022-04-27 19:37 UTC, cainlevy commented on src/components/Call/Call.tsx
> +        if (localVideo && !localVideo.paused) localVideo.paused = true;
🤔 why mutate `localVideo`? won't ccc's RoomClient do that?

2022-04-27 19:42 UTC, jackofsometrade commented on src/components/Call/Call.tsx
> +        if (localVideo && !localVideo.paused) localVideo.paused = true;
It only seems to do that when setLocalVideo is called (in ccc) which only sets paused = true when the user initiates a `toggleVideo` command.  This is represents some of the state stuff that I think could use a rethink.

2022-04-27 19:52 UTC, cainlevy commented on src/components/Call/Call.tsx
> +        if (localVideo && !localVideo.paused) localVideo.paused = true;
oh. sounds like RoomClient may need some additional logic for the new situation?

mutating react state is an anti-pattern because it does not trigger re-renders. it might also not persist between renders.

2022-04-27 19:53 UTC, jackofsometrade commented on src/components/Call/Call.tsx
> +        if (localVideo && !localVideo.paused) localVideo.paused = true;
Yeah I can see that now, I hadn't realized this before. I'll make some adjustments, thanks!

2022-05-02 16:45 UTC, jackofsometrade commented
@cainlevy Ping, hopefully last change needed :pray:

2022-05-02 18:06 UTC, cainlevy approved these changes

2022-05-03 21:49 UTC, merged