Lp calls
Ameelio/pathways-client pull request #29
Opened 2021-03-25 18:16 UTC by lspdrz

FIXES THE CALLS API INTEGRATION

2021-03-31 11:54 UTC, gabrielsaruhashi requested changes
some suggestions!

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/components/Calls/Calls.tsx
> +import { BaseCall, Call } from "src/types/Call";
delete unusued Call type import?
It's probably throwing a warning

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/redux/modules/connection.ts
> +    console.log("hey");
delete?

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/redux/modules/call.ts
> +  console.log("hey calls");
delete

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/redux/modules/call.ts
> +  if (!body.data) {
just move this to the fetchauthenticated call
I sent mark a screenshot on connect tech

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/redux/selectors.ts
> +  return { ...call };
just 
`return call `

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/types/Connection.ts
> +  lastCall: {
what is this for?
I think I commented on the backend PRs (if you replied, could you bump the thread? ), but why do this calculation server side? 
We should let clients do this expensive computation

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/types/Call.ts
> +  userParticipants: User[];
isnt the backend returning a userId array?
This should just be the inmateIds

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/types/Call.ts
> +  // connection: Connection;
and then here we have the users.
The point of this setup is to ensure data normalization. We already have this data from the connection redux model

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/redux/selectors.ts
>    // if (!kiosk) return;
you should be selecting the user from the connection array here

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/pages/Login/index.tsx
>          <Option value={facility.id}>{facility.name}</Option>
wait why keep this here?
It's odd to have a component be the dependency array - this is not a use case for useeffect imo

I'd just load the facilities data upon mounting on use effect
and then u render options.
We shouldn't be storing JSX elements in a useState variable

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/components/Dashboard/CallItem.tsx
> +            <Avatar src={call.userParticipants[0].profileImagePath} />
I think this a bit too unsafe...
I'd just map over the userparticipants array and render the Avatars

Also there might be more than two user participants registered for a call

2021-03-31 11:54 UTC, gabrielsaruhashi commented on src/api/Common.ts
> +    `${API_URL}public/facilities`,
maybe use that new URL() method?

2021-03-31 12:43 UTC, lspdrz commented on src/types/Connection.ts
> +  lastCall: {
Nah, we should always do expensive computation stuff on the server side. it's so much faster than on the browser and won't affect experience.

Good catch though because this backend change was on the first PR I did last week, I need to include that code in a new backend PR

2021-03-31 12:44 UTC, lspdrz commented on src/types/Call.ts
> +  userParticipants: User[];
Nah, it's returning the User objects which we need on the frontend

2021-03-31 12:46 UTC, lspdrz commented on src/types/Call.ts
> +  // connection: Connection;
I don't understand here

2021-03-31 12:57 UTC, lspdrz commented on src/components/Dashboard/CallItem.tsx
> +            <Avatar src={call.userParticipants[0].profileImagePath} />
Do we want to render all of the participants or just one? The designs only include one participant on the dashboard, but maybe that's because of our earlier assumption there would only ever be one connection

2021-03-31 12:59 UTC, lspdrz commented on src/api/Common.ts
> +    `${API_URL}public/facilities`,
I tried this for a while and had a problem, I don't remember what they were. I can try again if necessary

2021-04-01 14:21 UTC, gabrielsaruhashi requested changes
more feedback!

2021-04-01 14:21 UTC, gabrielsaruhashi commented on src/pages/Login/index.tsx
> +    <Option value={facility.id}>{facility.name}</Option>
you're missing a key here
react is gonna throw a warning/error bc they use these keys to optimize the rerendering strategy

2021-04-01 14:21 UTC, gabrielsaruhashi commented on src/api/Common.ts
> +  if (!body.data) {
wait why add this check?
I think response.status is enough

2021-04-01 14:21 UTC, gabrielsaruhashi commented on src/api/Common.ts
> +  if (!body.data) {
we should be checking for 200 and 201 btw

POST's return a 201 status code

2021-04-01 14:21 UTC, gabrielsaruhashi commented on src/redux/selectors.ts
>    // if (!kiosk) return;
the goal of this function is to retrieve the relationships of the call object.

that's why I was fetching the connection object. We use redux-toolkit entity adapter to normalize the data instead of duplicating it across multiple objects

e.g how are you currently getting the names of the participants? getCallEntities should iterate over the list of ids of outside users that will be on the call  to grab their information

2021-04-02 18:53 UTC, gabrielsaruhashi requested changes
last round of feedback!

2021-04-02 18:53 UTC, gabrielsaruhashi commented on src/components/Dashboard/ConnectionsList.tsx
>    const [connectionItems, setConnectionItems] = useState<JSX.Element[] | null>(
ok same comment here but we shouldnt be storing JSX in use state

this is what happens underneath the hood: https://reactjs.org/docs/lists-and-keys.html

2021-04-02 18:53 UTC, gabrielsaruhashi commented on src/redux/modules/contactsSlice.ts
> +      console.log("hi here in contact adapter");
delete?

2021-04-02 18:53 UTC, gabrielsaruhashi commented on src/redux/selectors.ts
> +  const connection = selectContactById(state, call.connectionId);
nit: change to contact?

2021-04-02 18:53 UTC, gabrielsaruhashi commented on src/redux/selectors.ts
> +  return call;
u need to return the contact here right?
rn u'r fetching the contact but not returning it with the call inffo

2021-04-02 18:53 UTC, gabrielsaruhashi commented on src/types/Connection.ts
> +  lastCall: {
why not use the Call object here?

2021-04-02 18:53 UTC, gabrielsaruhashi commented on src/types/User.ts
> +  lastCall: {
why not use the call object here?

2021-04-02 19:08 UTC, merged