Lp ipv
Ameelio/pathways-client pull request #56
Opened 2021-07-26 15:31 UTC by lspdrz

New IPV Feature

2021-07-28 01:40 UTC, gabrielsaruhashi requested changes
have some questions and suggestions!

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/pages/Dashboard/index.tsx
> +      joinCall={(meeting: Meeting) => {
does it make sense for joinCall to take a Meeting as the argument?
Shouldnt it just be Call?

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/pages/Dashboard/index.tsx
> +      dispatch(fetchInPersonVisits());
oh I dont think you need to included this here.
The only reason I have an interval here is in case the video handler information changes for the call. This wont happen for in person visits

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/types/InPersonVisit.ts
> +export interface BaseInPersonVisit extends BaseVisit {}
is this being used?

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/types/Meeting.ts
> +  scheduledStart: string;
which one is being use? Meeting or Call.ts?

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/types/Meeting.ts
> +type CustomFilter = string & { dummy?: never };
I dont think you need some of these types - cleanup?

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +  const [meetingCategory, setMeetingCategory] = useState<
would rename this meetingTypeFilter to make it more clear what it does

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +  >("");
would make this nullable, makes more sense with the filter implementation

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +  const [selectedContacts, setSelectedContacts] = useState<string[]>([]);
selectedContactsFilter

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +  const [selectedContacts, setSelectedContacts] = useState<string[]>([]);
would make this nullable in case the filter is not being used

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +      if (meetingCategory.length !== 0) {
check comments above! but if we make it nullable we wont have to make these awk length checks

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +        const name = `${meeting.userParticipants[0].firstName} ${meeting.userParticipants[0].lastName}`;
Why hardcode the 0 index ? 
We should map over all the participants. We're gonna add extra use rparticipants on the next sprint

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +    "call" | "inPersonContact" | "inPersonNoContact" | ""
would create a type on Meeting.ts callled MeetingType so we don't need to type this out in multiple placecs

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +        isOk = meeting.type === meetingCategory;
why not just return false here if the meeting does not pass this check?
Right now this makes these filter OR operators, but we probably want AND checks

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +        isOk = selectedContacts.includes(name);
same comment here re: returning false if it doesn't pass the active contact filter

We would then get rid of this mutable isOk variable

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +              openModal({ activeType: "CANCEL_CALL_MODAL", entity: meeting })
cancel meeting modal?

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +            style={{ paddingLeft: "0px" }}
tailwind

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +            onClick={() =>
move this to a Chip component? 
Seems like it's repeated logic

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +                    {/* <Tooltip title="PLACEHOLDER FOR liz">
we can delete! mb think i lef this in tthere

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +          <Typography.Text type="secondary" style={{ paddingBottom: "3px" }}>
tailwind

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +            <Button type="link" className="ant-dropdown-link">
do we need to hardcode the antd classname?

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +    let contacts = meetings.map(
there should be a util function in Call.ts that creates fulll names for all participants
if not we should probably move it there

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +    contacts = contacts.filter(
im a bit confused by this logic?
self is the contacts array itself, right?
what is this check doing? 
seeems like it will return true for everything

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +  const [activeMeetingTab, setActiveMeetingTab] = useState("allTypes");
would type it to ensure it's safe
using the keys you created for tablist

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +  const [activeMeetingTab, setActiveMeetingTab] = useState("allTypes");
can be a type we declare just for this page
no need to export it from somewhere else imoo

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +      );
nit: add whitespace between return statement and function?

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +                meeting={meeting as Meeting}
why do we need to force the typing here?

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +        index ===
a bit confused by this logic, not sure I understand what this self.findINdex is achieving -- there are two nested for loops? This would be n^2 right? 

but couldn't we just `groupBy` ahead of time and filter accordingly?

I have a groupby implementation in utils in the connect-client repo. I think it should be in this repo as well, but if not, you can just find it there

2021-07-28 01:40 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +    return dates.map((date) => {
coudlnt we just do this alll in one map instead of two consecutive ones?

2021-07-28 13:35 UTC, lspdrz commented on src/components/Modals/Modals.tsx
> +          cancelInPersonVisit={(id: string, reason: string) =>
It is the same modal that we use to cancel not both a call and in-person visit, but either a call or in-person-visit

2021-07-28 13:40 UTC, lspdrz commented on src/components/Dashboard/MeetingItem.tsx
> +        return "#569FE1";
Do we have an example of where we're using tailwind colors?

2021-07-28 13:41 UTC, lspdrz commented on src/components/Dashboard/MeetingItem.tsx
> +              {meeting.type === "call" && meeting.videoHandler && canJoin
I don't think it's a case statement, there's nested conditionals here

2021-07-28 13:45 UTC, lspdrz commented on src/types/Meeting.ts
> +  scheduledStart: string;
Meeting

2021-07-28 13:47 UTC, lspdrz commented on src/types/Meeting.ts
> +type CustomFilter = string & { dummy?: never };
i'd rather keep for consistency across codebases if needed?

2021-07-28 14:06 UTC, lspdrz commented on src/components/Meetings/Meetings.tsx
> +        isOk = selectedContacts.includes(name);
We want to check both filters

2021-07-28 14:07 UTC, lspdrz commented on src/components/Meetings/Meetings.tsx
> +            onClick={() =>
chip component?

2021-07-28 14:09 UTC, lspdrz commented on src/components/Meetings/Meetings.tsx
> +            <Button type="link" className="ant-dropdown-link">
yeah that's what the docs did

2021-07-28 14:12 UTC, lspdrz commented on src/components/Meetings/Meetings.tsx
> +    contacts = contacts.filter(
It's deleting all the duplicate values from the array

2021-07-28 14:17 UTC, lspdrz commented on src/components/Dashboard/MeetingsList.tsx
> +                meeting={meeting as Meeting}
no longer needed

2021-07-28 14:18 UTC, lspdrz commented on src/components/Dashboard/MeetingsList.tsx
> +        index ===
It's getting all of dates for the meetings, without any duplicates

2021-07-28 14:21 UTC, lspdrz commented on src/components/Dashboard/MeetingsList.tsx
> +  const [activeMeetingTab, setActiveMeetingTab] = useState("allTypes");
I can't type, it messes with antd

2021-08-18 11:44 UTC, lspdrz commented on src/types/Call.ts
> +  // userParticipants: Contact[];
Can you elaborate here?

2021-08-18 13:35 UTC, gabrielsaruhashi requested changes

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingItem.tsx
> +        marginBottom: "16px",
tailwind

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingItem.tsx
> +        marginBottom: "16px",
instead of harcoding a margin bottom on the meeting item level, I'd just add spacing on the parent div that wraps this list of items

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingItem.tsx
> +          {isInitializing ? (
let's move this to a separate function?
it's starting to get pretty complicated

Instead of having a disabled "join" button for in person visits, I'd just make it so that "view" details is always the active button for IPV.

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +      );
bumping request

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +      return (
could we move this into its own component?

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +    const meetingsByDate = filteredMeetings.filter(
could we type this variable to make it easier to read?

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +            style={{ paddingLeft: "0px" }}
bump

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +            onClick={() =>
I'd move it to its own component and call it Chip or something. It's being repeated 3 times rn

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +    contacts = contacts.filter(
wait why would there be a duplicate in the contact array?

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/types/Meeting.ts
> +type CustomFilter = string & { dummy?: never };
what is the use case of this dummy: never?

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Modals/Modals.tsx
> +          cancelInPersonVisit={(id: string, reason: string) =>
why not just have cancelMeeting here? 
cancelInPersonVisit and CancelMeetingModal both use the same endpoint don't they? 
And they call the same meeting ID

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +                <Space direction="vertical" style={{ paddingRight: "36px" }}>
tailwind

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +  const tableColumns = [
can we move the table to its own component? 
This file is a bit lengthy rn which makes it hard to read

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +        const name = `${meeting.userParticipants[0].firstName} ${meeting.userParticipants[0].lastName}`;
bump

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +        return <VideoCameraGray />;
seems like this icon logic is used in a couple of places.
Would move to a MeetingIcon component that takes the meeting type and an optional classname as a props

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/redux/modules/inPersonVisit.ts
> +const FETCH_IN_PERSON_VISITS = "inPersonVisits/fetchAll";
looking at the use cases for meetings on the pathways client, it seems to be we could just have a MeetingsSlice that has both IPV and the calls

It seems like in a couple of places of the codebase we're having to manually merge the two entities back together.

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/hooks/useMeetings.ts
> +  const [calls, setCalls] = useState<Meeting[]>([]);
see comment below! 
But I think we should merge the IPV and calls slice into a meetings slice given the use cases that we have

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +    const meetingsByDate = filteredMeetings.filter(
in this case, it seems to be just Meeting[]

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +    const meetingsByDate = filteredMeetings.filter(
could we call this uniqueMeetingDates?
Think it'd make it more clear what it does

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +          <Col flex="50px">
we're going to be using tablets real soon
to make this responsive, I'd use flex integers rather than hardcoding the pxs

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +      const meetingsAtDate = filteredMeetings.filter(
it seems like you're first getting the unique dates, then having to re-group all the meetings that happen at that date

Wouldn't it make more sense to just use groupby right away and avoid duplicating the effort to map over the array multiple times?

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +      const meetingsAtDate = filteredMeetings.filter(
there's a groupBy implementation in Common.ts that you can use

2021-08-18 13:35 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +  const [activeMeetingTab, setActiveMeetingTab] = useState("allTypes");
I think if you cast it back to string antd will be happy with it
That's what I've done in the past to keep the type safety check

2021-08-19 09:53 UTC, lspdrz commented on src/components/Dashboard/MeetingItem.tsx
> +        marginBottom: "16px",
Ok, I've added the tailwind styles but we still need to add the left border color like above. The tailwind classNames aren't working with the antd Card border default styles.

Do you have an example or idea of adding spacing on the parent div, I don't follow?

2021-08-19 10:00 UTC, lspdrz commented on src/components/Dashboard/MeetingsList.tsx
> +      return (
Sure, but why? It'll add another component to save 10 lines of code. Style choice, i guess. What should we call it? MeetingItemWrapper?

2021-08-19 10:21 UTC, lspdrz commented on src/components/Meetings/Meetings.tsx
> +                <Space direction="vertical" style={{ paddingRight: "36px" }}>
Contacts: there are duplicate contacts because that loops through all of the inmate's meetings, so there may be the same contact on multiple meetings

CustomFilter: I don't know, this was copied from Mark's types. Maybe he knows?

cancelnPersonVisit: legacy design, but they use separate language. Let's sort out in another PR? IT's working now

2021-08-19 10:40 UTC, lspdrz commented on src/components/Meetings/Meetings.tsx
> +        return <VideoCameraGray />;
It's only being used in the MeetingTable. The one in the MeetingItem uses different icons

2021-08-19 10:40 UTC, lspdrz commented on src/redux/modules/inPersonVisit.ts
> +const FETCH_IN_PERSON_VISITS = "inPersonVisits/fetchAll";
Yep, agreed. I think we can create a /meetings endpoint that returns both calls and ipvs and use that for pathways

2021-08-19 10:41 UTC, lspdrz commented on src/hooks/useMeetings.ts
> +  const [calls, setCalls] = useState<Meeting[]>([]);
I agree but I think we should do in a new story

2021-08-19 10:48 UTC, lspdrz commented on src/components/Dashboard/MeetingsList.tsx
> +      const meetingsAtDate = filteredMeetings.filter(
I can't find that in Common.ts

2021-08-19 13:37 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +            <Button type="link" className="ant-dropdown-link">
have u tried without it? I dont think it's needed

2021-08-19 13:39 UTC, lspdrz commented on src/components/Dashboard/MeetingsList.tsx
> +  const [activeMeetingTab, setActiveMeetingTab] = useState("allTypes");
I don't know what you mean here

2021-08-19 13:39 UTC, lspdrz commented on src/components/Meetings/Meetings.tsx
> +    contacts = contacts.filter(
Because this loops through all of the inmate meetings, there might be the same contact on multiple meetings

2021-08-19 13:40 UTC, lspdrz commented on src/components/Meetings/Meetings.tsx
> +            <Button type="link" className="ant-dropdown-link">
It's for the styling, I think. I can try it without

2021-08-19 13:40 UTC, lspdrz commented on src/components/Modals/Modals.tsx
> +          cancelInPersonVisit={(id: string, reason: string) =>
Job for a new story

2021-08-19 13:41 UTC, lspdrz commented on src/types/Meeting.ts
> +type CustomFilter = string & { dummy?: never };
I don't know, I copied this over from mark's types

2021-08-20 13:48 UTC, gabrielsaruhashi requested changes
last round of requests!

2021-08-20 13:48 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingItem.tsx
> +  const getIcon = () => {
could we move this to a component? MeetingIcon
It's gonna be used in other places

2021-08-20 13:48 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +  const [activeMeetingTab, setActiveMeetingTab] = useState("allTypes");
you can cast a variable in TS if you're confident that it's what you expect
literally:
activeMeetingTab as string

2021-08-20 13:48 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingsList.tsx
> +          <Col flex={0.1}>
trying to understand what's the intended behavior here - is the idea that it simply occupies the minimum amount of space needed? 
If yes I'd do flex="none"

2021-08-20 13:48 UTC, gabrielsaruhashi commented on src/components/Dashboard/MeetingItem.tsx
> +        return "#F66262";
bumping this request
cool if we do it in a fast-follow PR, but think it's important to update the palette

2021-08-20 13:48 UTC, gabrielsaruhashi commented on src/components/Meetings/Chip.tsx
> +        style={{ paddingLeft: "0px" }}
is this overriding the antd css?

2021-08-20 13:48 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +        <Row>
nit: i dont think you need to wrap it in a Row here

2021-08-20 13:48 UTC, gabrielsaruhashi commented on src/components/Meetings/Meetings.tsx
> +    let contacts = [];
@lspdrz why not just pull all contacts directly from the contacts slice? 
It might be off-putting to not see all your approved contacts on your list even if you dont have any scheduled meetings with them. It might seem you dont have the ability to scheduled meetings with them

2021-08-20 13:48 UTC, gabrielsaruhashi commented on src/components/Meetings/MeetingsTable.tsx
> +  const getIcon = (visitType: MeetingType) => {
^ bumping request to move it to a MeetingComponent

2021-08-20 13:48 UTC, gabrielsaruhashi commented on src/components/Meetings/MeetingsTable.tsx
> +    return meetings.filter((meeting) => {
.filter always returns a new object, so this will keep being re-computed

I'd either create a filterdVisits useState() and update it using a useEffect (preferably) or memoize this function

2021-08-20 13:48 UTC, gabrielsaruhashi commented on tailwind.config.js
> +        // 50: '#fafafa',
delete?

2021-08-20 14:12 UTC, gabrielsaruhashi approved these changes

2021-08-24 11:59 UTC, lspdrz commented on src/components/Dashboard/MeetingsList.tsx
> +          <Col flex={0.1}>
flex="none" doesn't work. I'm trying to get a certain amount of distance between the columns: ![image](https://user-images.githubusercontent.com/9705113/130612587-e6b1383a-59c5-4e66-b7bd-9c4dd287a8eb.png)

2021-08-24 12:00 UTC, lspdrz commented on src/components/Dashboard/MeetingsList.tsx
> +  const [activeMeetingTab, setActiveMeetingTab] = useState("allTypes");
Not sure what we want here?

2021-08-24 12:00 UTC, lspdrz commented on src/components/Dashboard/MeetingsList.tsx
> +  const [activeMeetingTab, setActiveMeetingTab] = useState("allTypes");
OH, i see, i see

2021-08-24 12:08 UTC, lspdrz commented on src/components/Dashboard/MeetingItem.tsx
> +        return "#F66262";
I responded to this elsewhere, but we have to do it this way herre because if I do this style via tailwind the antd component overrides it.

2021-08-24 12:08 UTC, lspdrz commented on src/components/Meetings/Chip.tsx
> +        style={{ paddingLeft: "0px" }}
Yes

2021-08-24 12:18 UTC, lspdrz commented on src/components/Meetings/Meetings.tsx
> +    let contacts = [];
This is a new story, changes multiple files.

2021-08-24 12:19 UTC, lspdrz commented on src/components/Meetings/MeetingsTable.tsx
> +  const getIcon = (visitType: MeetingType) => {
What do you mean MeetingComponent?

2021-08-25 10:34 UTC, lspdrz commented on src/components/Modals/Modals.tsx
> +          cancelInPersonVisit={(id: string, reason: string) =>
https://app.clubhouse.io/ameelio/story/304/change-cancelmeetingmodal-on-pathways-to-use-same-dispatch-functions

2021-08-25 10:47 UTC, lspdrz commented on src/components/Meetings/Meetings.tsx
> +    let contacts = [];
https://app.clubhouse.io/ameelio/story/305/change-meetings-contact-fetching

2021-08-25 10:50 UTC, lspdrz commented on src/hooks/useMeetings.ts
> +  const [calls, setCalls] = useState<Meeting[]>([]);
https://app.clubhouse.io/ameelio/story/306/move-calls-and-ipv-slices-into-one-meetings-slice

2021-08-25 12:58 UTC, merged